(alias
 (name runtest)
 (deps
  (alias_rec all)))

(coq.theory
 (name Rocqet.Tests)
 (theories Rocqet)
 (modules
  ;Handler_types
  ;Closing_facts_test
  ;C_compcert
  ;Opaque_override 
  ;Linkage_concat
  ;Demo
  ;STLC
  ;Mixin_test
  ;STLCCompiler
  ;Wrong_arg
  ;CompCert
  ;Wrong_extend
  ;Flexible
  ;Flexible_2
  ;Multiple_FRecursion
  ;Mixin
  ;Salad
  ;Path_subst_ind
  ;Inherit_name
  ;Play
  ;Reparam_test
  ;STLC_prec
  ;Opaque_linkage_concat
  ;Nested_fsimpl
  ;STLC_trait
  ;STLC_mind 
  ;Ext_mind
  ;Conformance_opt
  ;Final_families
  ;Conformance_opt2
  ;Trait_no_base
  ;STLC_mind2 
  ;Same_Diff_Reparam
  ;Default_handler
  ;Path_subst_hard
  ;Inherit_mutual 
  ;MetaData_bound_names
  ;Extend_with_mutual
  ;Inherit_directly
  ;STLC_base
  ;STLC_bool
  ;STLC_prod
  ;STLC_all
  ;STLC_horizon
  ;STLC_horizontal
  ))
