(alias
 (name runtest)
 (deps
  (alias_rec all)))

(coq.theory
 (name NFPOP.Tests)
 (theories NFPOP)
 (modules
  ;Handler_types
  ;Closing_facts_test
  ;C_compcert
  ;Opaque_override 
  ;Linkage_concat
  ;Demo
  ;STLC
  ;Mixin_test
  ;STLCCompiler
  ;Wrong_arg
  ;CompCert
  ;Wrong_extend
  ;Flexible
  ;Flexible_2
  ;Multiple_FRecursion
  ;Mixin
  ;Salad
  ;Path_subst_ind
  ;Inherit_name
  ;Play
  ;Reparam_test
  ;STLC_prec
  ;Opaque_linkage_concat
  ;Nested_fsimpl
  ;STLC_trait
  ))
