family Impzero.Imp extends SourceLanguage {
    Inductive expression : Type += ...   

    Inductive statement : Type += ...      
    
    family Semantics {            
      Inductive cont : Type += ...        

      Inductive step : state -> state -> Prop = ...      
    }    
}
