(include_subdirs qualified)

(coq.theory
 (name Rocqet.CompCert)
 ;; 
 (theories Flocq Rocqet)
 (modules   
   ;Imp

   ; CompCert libraries
   lib/Coqlib
   lib/AST
   lib/Builtins0
   lib/Events
   lib/Intv   
   lib/Archi   
   lib/Builtins1   
   lib/Linking
   lib/Ordered   
   lib/Floats
   lib/Maps   
   lib/Values
   lib/Axioms   
   lib/Globalenvs
   lib/Memdata           
   lib/Zbits   
   lib/Ctypes
   lib/IEEE754_extra
   lib/Memory
   lib/Smallstep
   lib/Builtins
   lib/Errors
   lib/Integers
   lib/Memtype
   lib/Cop
   lib/Mon
   lib/Prelude
   lib/Registers
   lib/Decidableplus
   lib/Machregs
   lib/Locations
   lib/Conventions1
   lib/Mregisters
   lib/RTLmonad
   lib/Heaps
   lib/Kildall
   lib/Lattice
   lib/Iteration
   lib/Wfsimpl   
   lib/Bounds
   lib/Separation
   lib/Stacklayout
  ))


