(* Implight IR *)
family Impzero.Implight extends SourceLanguage {
  Inductive expression : Type += ...

  Inductive statement : Type += ... 

  family Semantics {
      Inductive cont : Type += ...

      Inductive step : Type += ...
  }
}

(* Simplify Expression *)
(* Translation from Imp -> Implight *)
family Impzero.ImpgenSimplExpr {
   family Source extends Imp { }
   family Target extends Implight { }
     
    Definition translate_constant := ...
    Fixpoint translate_expression := ...
    Fixpoint translate_statement := ...
   
   family Proofs {
     Inductive match_cont := ...

     Inductive match_states := ...

     Lemma translate_initial_states : ...

     Lemma translate_final_states: ...

     Theorem translate_program_correct : ...
   }
}
